//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFilm2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Histories = new HashSet<History>();
        }
    
        public int film_id { get; set; }
        public string fname { get; set; }
        public string fname_eng { get; set; }
        public int type_id { get; set; }
        public int country_id { get; set; }
        public short year { get; set; }
        public int season_id { get; set; }
        public int episode_id { get; set; }
        public string description { get; set; }
        public string AspUserId { get; set; }
        public virtual Country Country { get; set; }
        public virtual Episode Episode { get; set; }
        public virtual Season Season { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> Histories { get; set; }
    }
}
