//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFilm2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_History
    {
        public int history_id { get; set; }
        public string fname { get; set; }
        public string tname { get; set; }
        public string sname { get; set; }
        public string ename { get; set; }
        public System.DateTime hdate { get; set; }
        public string AspUserId { get; set; }
    }
}
